name: Frontend

on:
  workflow_dispatch:

permissions:
  packages: write
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Octopus Deploy
        uses: OctopusDeploy/login@v1.0.1
        with:
           server: "https://adamclose.octopus.app/"
           service_account_id: "7bca9f0c-70a6-4e95-a9ff-6aae2d170d43"
      
      - name: Set Version
        run: echo "PACKAGE_VERSION=$(date +'%Y.%m.%d').$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build Docker Frontend image
        run: docker build -f ./frontend/Dockerfile -t adamoctoclose/payments-frontend:${{ env.PACKAGE_VERSION }} ./frontend


      - name: Push Docker Front image to Docker Hub
        run: docker push adamoctoclose/payments-frontend:${{ env.PACKAGE_VERSION }}
        
      - name: Push Build Information to Octopus
        uses: OctopusDeploy/push-build-information-action@v3
        with:
            space: Retail Banking
            packages: | 
              payments-frontend
            version: ${{ env.PACKAGE_VERSION }}
